#! /usr/bin/env python
# -*- coding: iso-8859-1 -*-

# chimera - observatory automation system
# Copyright (C) 2006-2007  P. Henrique Silva <henrique@astro.ufsc.br>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

from chimera.core.cli import ChimeraCLI, action, parameter, ParameterType
from chimera.core.callback import callback
from chimera.util.output import blue, green, red, yellow
from chimera_autoalign.controllers.m2control import State
#from chimera.core.exceptions import ChimeraException
from astropy import units as u

import sys
import time
import os
import re

class ChimeraM2Control(ChimeraCLI):

    def __init__(self):
        ChimeraCLI.__init__(
            self, "chimera-m2control", "Focuser/Hexapod controller", 0.1, port=9004)

        self.addHelpGroup("FOCUS", "Focus")
        self.addInstrument(name="m2control",
                           cls="M2Control",
                           required=True,
                           helpGroup="M2Control",
                           help="M2Control controller to be used")

        self.addInstrument(name="tel",
                           cls="Telescope",
                           required=True,
                           helpGroup="M2Control",
                           help="Telescope controller to be used")

        self.addParameters(dict(name="name",
                                long="name",
                                helpGroup="",
                                default="",
                                help="Name to use for the current state on lookup table.",
                                metavar="FILENAME"))

        self.addParameters(dict(name="filename",
                                long="file",
                                short="f",
                                helpGroup="",
                                default=None,
                                help="Filename of the lookup table.",
                                metavar="FILENAME"))

    @action(helpGroup="ACTION",
            help="Display information about m2 control law.")
    def info(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        state = self.m2control.getState()
        if state == State.ACTIVE:
            color = green
        else:
            color = red

        self.out('Current state: %s ' % color(state.__str__()))

        self.out("Reference position/offset:")
        position = self.m2control.getRefPos() #getCurrentSavedPos()
        offset = self.m2control.getRefOffset()

        self.out('# X: %12s / %12s\n'
                 '# Y: %12s / %12s\n'
                 '# Z: %12s / %12s (focus)\n'
                 '# U: %12s / %12s\n'
                 '# V: %12s / %12s\n' % (position.x, offset.x,
                                         position.y, offset.y,
                                         position.z, offset.z,
                                         position.u, offset.u,
                                         position.v, offset.v))

        # self.out("Reference offset:")

        self.out("Lookup Table (%s):" % (self.m2control["table"]))
        self.out("Number of points: %i" % len(self.m2control.getLookupTable()))

    @action(helpGroup="ACTION",
            help="load lookuptable.")
    def load(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        if not options.filename:
            self.exit("No table. Use \'-f\' option.")

        self.out("Loading lookuptable from %s " % options.filename, end="")
        try:
            self.m2control.loadLookupTable(options.filename)
        except Exception,e:
            self.exit(red("FAILED"))
        else:
            self.exit(green("OK"))


    @action(helpGroup="ACTION",
            help="Plot lookuptable data points.")
    def show_table(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        import matplotlib.pyplot as plt
        import numpy as np
        plt.clf()
        ax = plt.subplot(111, projection='polar')
        ax.set_theta_zero_location("N")
        lookuptable = self.m2control.getLookupTable()
        ax.scatter(lookuptable["AZ"] * np.pi / 180., 90 - lookuptable["ALT"], marker = '.',
                   color='r', alpha=1, s=20)
        ax.grid(True)
        # ax.set_ylim(90 - altitude_min + 10, 0)
        ax.set_yticklabels(90 - np.array(ax.get_yticks(), dtype=int))
        plt.show()

    @action(helpGroup="ACTION",
            help="Update position of the hexapod based on the lookuptable.")
    def update(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        state = self.m2control.getState()
        if state == State.ACTIVE:
            self.exit("Controller state is %s. Stop it before manually updating." % green(state.__str__()))

        self.out("Updating M2 position.", end="")
        try:
            self.m2control.update()
        except:
            self.exit(red("FAILED"))

        self.out(green("OK"))

    @action(helpGroup="ACTION",
            help="Start M2 control law.")
    def activate(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out("Activating M2 control law loop.", end="")
        self.m2control.activate()
        self.out(green("OK"))

    @action(helpGroup="ACTION",
            help="Start M2 control law.")
    def monitor(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        @callback(self.localManager)
        def updateComplete(position):

            ostr = ''
            for p in position:
                ostr += '%+6.3f '% p[0]
            self.out(ostr)

        self.m2control.updateComplete += updateComplete

        self.wait(abort=False)

    @action(helpGroup="ACTION",
            help="Stop M2 control law.")
    def deactivate(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out("Deactivating M2 control law loop.", end="")
        self.m2control.deactivate()
        self.out(green("OK"))

    @action(helpGroup="ACTION",
            help="Add current telescope and focuser state to lookup table.")
    def add(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out("Adding current state to lookup table.")
        self.m2control.add(options.name)
        self.out(green("OK"))

    @action(helpGroup="ACTION",
            help="Add current telescope and focuser state to lookup table.")
    def calibrate(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        state = self.m2control.getState()
        if state == State.ACTIVE:
            self.exit("[%s] Controller state is %s. Stop it before calibrating." % (red("ERROR"),
                                                                                    green(state.__str__())))

        self.out("Calibrating lookuptable")
        self.m2control.calibrate()
        self.out(green("OK"))

    @action(helpGroup="ACTION",
            help="Save lookup table to a fits file.")
    def save(self, options):

        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        if options.filename is not None:
            self.out("Saving lookup table to %s." % options.filename)
            self.m2control.saveLookupTable(options.filename)
            self.out(green("OK"))
        else:
            self.out('[%s] No file to save to. Give filenema with \'-f\'' % (red('FAIL')))

    @action(name="set_curr_pos", long="set-current-position",
            helpGroup="ACTION",
            help="Set reference position.")
    def setcurrpos(self, options):
        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out('Setting reference position.')
        self.m2control.savePosition()

    @action(name="set_ref_pos", long="set-reference-position",
            helpGroup="ACTION",
            help="Set reference position.")
    def setrefpos(self, options):
        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out('Setting reference position.')
        self.m2control.setRefPos()

    @action(name="set_ref_offset", long="set-reference-offset",
            helpGroup="ACTION",
            help="Set reference offset.")
    def setrefoffset(self, options):
        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out('Setting reference offset.')
        self.m2control.setRefOffset()

    @action(name="set_offset", long="set-offset",
            helpGroup="ACTION",
            help="Set offset with respect to current position.")
    def setoffset(self, options):
        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out('Setting reference offset.')
        self.m2control.setupOffset()

    @action(name="reset", long="reset",
            helpGroup="ACTION",
            help="Reset current position and offset to zero.")
    def setrefoffset(self, options):
        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out('Resetting.')
        self.m2control.reset()

    @action(name="go-to-reference", long="go-to-reference-position",
            helpGroup="ACTION",
            help="Go to reference position. Usefull when looses reference.")
    def gorefoffset(self, options):
        if not self.m2control:
            self.exit(
                "No Autoalign controller available. Try --autofocus=..., or --help.")

        self.out('Going to reference position.')
        self.m2control.goRefPos()

    # def __abort__(self):
    #     self.out("\naborting... ", end="")
    #
    #     # copy self.skyflat Proxy because we are running from a differente
    #     # thread (yes, Pyro is tricky!)
    #     autoalign = copy.copy(self.autoalign)
    #     autoalign.abort()

def main():
    cli = ChimeraM2Control()
    cli.run(sys.argv)
    cli.wait()

if __name__ == '__main__':

    main()
